CREATE DATABASE IF NOT EXISTS F1Network;

USE F1Network;

CREATE TABLE IF NOT EXISTS Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pubblish_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    content VARCHAR(200) NOT NULL,
    image_url VARCHAR(100),
    user_id INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Comments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pubblish_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    content VARCHAR(200) NOT NULL,
    post_id INT NOT NULL,
    user_id INT NOT NULL,
    FOREIGN KEY (post_id) REFERENCES Posts(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

